import streamlit as st
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel


data = {
    'id': [f'item-{i}' for i in range(1, 202)],
    'title': [
        # 1-50: Competitive programming & Python
        'Introduction to Competitive Programming',
        'Hackathons for Skill Development',
        'Python Programming Basics',
        'Advanced Python Programming',
        'Data Structures with Python',
        'Algorithms for Beginners',
        'Advanced Algorithms',
        'Problem Solving Strategies',
        'Recursion Techniques',
        'Dynamic Programming Introduction',
        'Greedy Algorithms in Practice',
        'Graph Algorithms',
        'Tree Data Structures',
        'Heap and Priority Queues',
        'Sorting and Searching Techniques',
        'Big O Notation and Complexity',
        'Python Libraries for Programming',
        'Python Debugging Techniques',
        'Python Testing and TDD',
        'Project-based Python Learning',
        'Competitive Programming Platforms',
        'Top Coding Challenges',
        'Hackerrank and Leetcode Practice',
        'Interview Coding Questions',
        'Data Structures and Algorithms Round Preparation',
        'Python Automation Scripts',
        'Python for Data Analysis',
        'Python for Web Development',
        'Python for Scripting',
        'Python Best Practices',
        'Object-Oriented Programming in Python',
        'Functional Programming in Python',
        'Python File Handling',
        'Python Regular Expressions',
        'Python Networking Modules',
        'Python Multithreading',
        'Python Async Programming',
        'Python Logging and Debugging',
        'Python API Integration',
        'Python Unit Testing',
        'Python Packaging and Modules',
        'Python Virtual Environments',
        'Python for Machine Learning',
        'Python Pandas Tutorial',
        'Python NumPy Tutorial',
        'Python Matplotlib Tutorial',
        'Python Seaborn Tutorial',
        'Python for Data Visualization',
        'Python for Financial Analysis',
        'Python for Scientific Computing',
        'Python Web Scraping Techniques',
        # 51-100: Machine Learning & AI
        'Introduction to Machine Learning',
        'Supervised Learning Algorithms',
        'Unsupervised Learning Algorithms',
        'Reinforcement Learning Basics',
        'Deep Learning Introduction',
        'Convolutional Neural Networks',
        'Recurrent Neural Networks',
        'Generative Adversarial Networks',
        'Natural Language Processing Basics',
        'Text Preprocessing Techniques',
        'Sentiment Analysis Projects',
        'Named Entity Recognition',
        'Text Classification with Python',
        'Word Embeddings with Word2Vec',
        'Transformer Models Introduction',
        'BERT for NLP Tasks',
        'GPT Models Overview',
        'Attention Mechanism in Neural Networks',
        'AI Ethics and Bias',
        'Explainable AI Techniques',
        'Machine Learning Pipelines',
        'Feature Engineering Techniques',
        'Hyperparameter Tuning',
        'Model Evaluation Metrics',
        'Cross Validation Techniques',
        'Overfitting and Regularization',
        'Gradient Boosting Algorithms',
        'XGBoost Tutorial',
        'LightGBM Tutorial',
        'CatBoost Tutorial',
        'Decision Trees and Random Forests',
        'Support Vector Machines',
        'K-Nearest Neighbors Algorithm',
        'Clustering Algorithms',
        'K-Means Clustering',
        'Hierarchical Clustering',
        'PCA and Dimensionality Reduction',
        'Time Series Analysis in Python',
        'Forecasting Techniques',
        'Anomaly Detection Projects',
        'AI Project Ideas for Portfolio',
        'Machine Learning Projects with Python',
        'Deep Learning Projects',
        'Computer Vision Projects',
        'Image Classification Projects',
        'Object Detection Projects',
        'Reinforcement Learning Projects',
        'ML for Healthcare Projects',
        'ML for Finance Projects',
        'ML for Marketing Projects',
        # 101-150: Cloud, DevOps, Company Internships
        'AWS Cloud Computing Basics',
        'Microsoft Azure Fundamentals',
        'Google Cloud Platform Overview',
        'Docker and Containerization',
        'Kubernetes Basics',
        'CI/CD Pipeline Setup',
        'Jenkins for DevOps',
        'Version Control with Git and GitHub',
        'GitHub Actions for Automation',
        'Terraform for Cloud Infrastructure',
        'Ansible for Configuration Management',
        'Monitoring with Prometheus and Grafana',
        'Serverless Computing with AWS Lambda',
        'Cloud Storage Solutions',
        'Data Pipelines in Cloud',
        'ML Deployment in Cloud',
        'API Development and Integration',
        'REST API with Flask',
        'REST API with FastAPI',
        'GraphQL API Introduction',
        'Building Web Apps with Streamlit',
        'Building Web Apps with Dash',
        'Remote Jobs Opportunities in Tech',
        'Internship Opportunities in Startups',
        'Google Internship Guide',
        'Microsoft Careers Overview',
        'Amazon Jobs for Data Scientists',
        'Facebook AI Research Internships',
        'LinkedIn Learning Resources',
        'Career Growth in AI and ML',
        'Resume Building Tips for Tech',
        'Interview Preparation Strategies',
        'Cracking Google Interviews',
        'Cracking Microsoft Interviews',
        'Cracking Amazon Interviews',
        'Tech Company Recruitment Process',
        'Job Opportunities for ML Engineers',
        'Networking and Mentorship Programs',
        'Tips for Tech Hackathons',
        'Portfolio Development for Programmers',
        'Open Source Contributions Guide',
        'Freelancing as a Python Developer',
        'Career Advice for College Students',
        'LinkedIn Networking Tips',
        'Remote Internship Experiences',
        'Internship Tips for Google & Microsoft',
        'Top Coding Competitions Worldwide',
        'Online Courses for Skill Improvement',
        'Bootcamps for Data Science and ML',
        'Scholarships for AI & ML Students',
        # 151-200: Misc Tech, Advanced Topics, More Internships
        'Big Data and Hadoop Essentials',
        'Spark for Big Data Analytics',
        'Kafka for Real-time Data',
        'ETL Processes in Data Engineering',
        'SQL and Databases for Data Science',
        'NoSQL Databases Introduction',
        'Graph Databases with Neo4j',
        'Data Warehousing Concepts',
        'Business Intelligence with PowerBI',
        'Data Visualization with Tableau',
        'Time Series Forecasting Projects',
        'Predictive Analytics Projects',
        'Recommender Systems Projects',
        'AI for Healthcare',
        'AI for Finance',
        'AI for Retail',
        'AI for Marketing',
        'AI Industry Trends',
        'Understanding AI Ethics',
        'Fairness in AI Models',
        'Bias Mitigation Techniques',
        'Explainable AI Projects',
        'ML Model Deployment Strategies',
        'Containerizing ML Applications',
        'Model Monitoring and Logging',
        'MLOps Best Practices',
        'Data Versioning Techniques',
        'Experiment Tracking in ML',
        'Hyperparameter Optimization Projects',
        'Ensemble Learning Techniques',
        'Stacking and Blending Models',
        'Dimensionality Reduction Projects',
        'Feature Selection Techniques',
        'Time Series ML Projects',
        'Fraud Detection Projects',
        'Recommendation Engine Projects',
        'AI Chatbots Development',
        'Speech Recognition Projects',
        'Image Generation with GANs',
        'Style Transfer Projects',
        'Self-supervised Learning Projects',
        'Few-shot Learning Projects',
        'Transfer Learning Projects',
        'Advanced NLP Projects',
        'Text Summarization Projects',
        'Machine Translation Projects',
        'Question Answering Systems',
        'Semantic Search Projects',
        'AI Model Interpretability Projects',
        'Advanced Python for ML'
    ],
    'content': [
        # 1-50
        'Competitive Programming is about problem solving and algorithms',
        'Hackathons improve coding skills, teamwork, and creativity',
        'Python programming teaches basics of syntax and logic',
        'Advanced Python for real-world projects',
        'Data Structures are essential for efficient programming',
        'Algorithms help solve computational problems efficiently',
        'Advanced algorithms for complex problems',
        'Problem solving strategies for coding competitions',
        'Recursion techniques for programming challenges',
        'Dynamic Programming introduction and examples',
        'Greedy algorithms for optimization problems',
        'Graph algorithms for shortest paths and traversals',
        'Trees and binary trees in programming',
        'Heap and priority queue implementations',
        'Sorting and searching algorithms',
        'Understanding Big O notation and complexity',
        'Python libraries to enhance programming',
        'Debugging techniques in Python',
        'Unit testing in Python projects',
        'Project-based Python learning examples',
        'Best competitive programming platforms',
        'Top coding challenges to improve skills',
        'HackerRank and LeetCode practice problems',
        'Important interview coding questions',
        'DSA round preparation for top companies',
        'Python automation scripts for productivity',
        'Python for data analysis using Pandas',
        'Python for web development with Flask',
        'Python scripting for daily tasks',
        'Python best coding practices',
        'Object-Oriented Programming concepts',
        'Functional programming with Python',
        'File handling and manipulation in Python',
        'Regular expressions for text parsing',
        'Networking modules in Python',
        'Multithreading and concurrency in Python',
        'Async programming for efficiency',
        'Logging and debugging in Python applications',
        'Python API integration examples',
        'Unit testing and CI/CD with Python',
        'Python packaging and modules',
        'Virtual environments in Python',
        'Python libraries for ML projects',
        'Pandas for data analysis',
        'NumPy for numerical computing',
        'Matplotlib for plotting and visualization',
        'Seaborn for statistical data visualization',
        'Data visualization for insights',
        'Financial analysis projects with Python',
        'Scientific computing using Python',
        'Web scraping projects using Python',
        # 51-100
        'Intro to ML concepts and algorithms',
        'Supervised learning algorithms explained',
        'Unsupervised learning algorithms explained',
        'Introduction to reinforcement learning',
        'Deep learning introduction and concepts',
        'CNN for image classification projects',
        'RNN for sequence modeling',
        'GANs for image generation',
        'NLP projects with Python',
        'Text preprocessing techniques in NLP',
        'Sentiment analysis project using Python',
        'Named entity recognition project',
        'Text classification with machine learning',
        'Word embeddings with Word2Vec',
        'Transformer models for NLP',
        'BERT for NLP tasks',
        'GPT models for natural language generation',
        'Attention mechanism in neural networks',
        'AI ethics and bias management',
        'Explainable AI techniques',
        'ML pipelines and workflow',
        'Feature engineering for ML models',
        'Hyperparameter tuning examples',
        'Model evaluation metrics explained',
        'Cross validation techniques for ML',
        'Overfitting and regularization strategies',
        'Gradient boosting algorithms',
        'XGBoost implementation examples',
        'LightGBM implementation examples',
        'CatBoost implementation examples',
        'Decision trees and random forests',
        'Support vector machines in practice',
        'K-Nearest Neighbors implementation',
        'Clustering algorithms in ML',
        'K-Means clustering projects',
        'Hierarchical clustering explained',
        'PCA and dimensionality reduction',
        'Time series analysis projects',
        'Forecasting techniques in Python',
        'Anomaly detection in data',
        'AI project ideas for portfolio',
        'ML projects implemented with Python',
        'Deep learning project examples',
        'Computer vision project ideas',
        'Image classification with CNN',
        'Object detection projects',
        'Reinforcement learning projects',
        'ML applications in healthcare',
        'ML applications in finance',
        'ML applications in marketing',
        # 101-150
        'AWS cloud computing fundamentals',
        'Microsoft Azure fundamentals',
        'Google Cloud Platform overview',
        'Docker containerization projects',
        'Kubernetes basics for deployment',
        'CI/CD pipeline setup examples',
        'Jenkins for DevOps projects',
        'Version control with Git and GitHub',
        'GitHub actions for automation',
        'Terraform for cloud infrastructure',
        'Ansible configuration management',
        'Monitoring with Prometheus and Grafana',
        'Serverless computing with AWS Lambda',
        'Cloud storage solutions overview',
        'Data pipelines in cloud projects',
        'Deploy ML models in cloud',
        'API development and integration',
        'REST API development with Flask',
        'REST API with FastAPI',
        'GraphQL API introduction',
        'Web apps with Streamlit',
        'Web apps with Dash',
        'Remote jobs in tech industry',
        'Internships in startups and SMEs',
        'Google internship program guide',
        'Microsoft career paths overview',
        'Amazon jobs for ML engineers',
        'Facebook AI research internships',
        'LinkedIn learning resources',
        'Career growth in AI and ML fields',
        'Resume building for tech jobs',
        'Interview prep strategies',
        'Google interview preparation',
        'Microsoft interview preparation',
        'Amazon interview preparation',
        'Recruitment process in top tech companies',
        'Job opportunities for ML engineers',
        'Networking and mentorship programs',
        'Tech hackathon tips',
        'Portfolio development for programmers',
        'Open source contribution guide',
        'Freelancing as Python developer',
        'Career advice for college students',
        'LinkedIn networking strategies',
        'Remote internship experiences',
        'Google and Microsoft internship tips',
        'Top coding competitions worldwide',
        'Online courses to improve skills',
        'Bootcamps for Data Science and ML',
        'Scholarships for AI & ML students',
        # 151-200
        'Big data and Hadoop essentials',
        'Spark for big data analytics',
        'Kafka for real-time data',
        'ETL processes in data engineering',
        'SQL and database management',
        'NoSQL databases introduction',
        'Graph databases with Neo4j',
        'Data warehousing concepts',
        'Business intelligence with PowerBI',
        'Data visualization with Tableau',
        'Time series forecasting projects',
        'Predictive analytics projects',
        'Recommender systems projects',
        'AI applications in healthcare',
        'AI applications in finance',
        'AI applications in retail',
        'AI applications in marketing',
        'AI industry trends analysis',
        'Understanding AI ethics',
        'Fairness in AI models',
        'Bias mitigation techniques in AI',
        'Explainable AI projects',
        'ML model deployment strategies',
        'Containerizing ML applications',
        'Model monitoring and logging',
        'MLOps best practices',
        'Data versioning techniques',
        'Experiment tracking in ML',
        'Hyperparameter optimization projects',
        'Ensemble learning techniques',
        'Stacking and blending models',
        'Dimensionality reduction projects',
        'Feature selection techniques',
        'Time series ML projects',
        'Fraud detection projects',
        'Recommendation engine projects',
        'AI chatbot development',
        'Speech recognition projects',
        'Image generation with GANs',
        'Style transfer projects',
        'Self-supervised learning projects',
        'Few-shot learning projects',
        'Transfer learning projects',
        'Advanced NLP projects',
        'Text summarization projects',
        'Machine translation projects',
        'Question answering systems',
        'Semantic search projects',
        'AI model interpretability projects',
        'Advanced Python for ML'
    ]
}




df = pd.DataFrame(data)


# TF-IDF vectorizer

tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(df['content'])


# Recommendation Function

def get_recommendations_by_keyword(keyword, tfidf=tfidf, tfidf_matrix=tfidf_matrix, df=df):
    if not keyword.strip():
        return "Please enter a keyword or phrase."

    keyword_vec = tfidf.transform([keyword])
    cosine_sim = linear_kernel(keyword_vec, tfidf_matrix).flatten()
    top_indices = cosine_sim.argsort()[::-1][:5]

    recommendations = []
    for idx in top_indices:
        recommendations.append({
            'id': df.iloc[idx]['id'],
            'title': df.iloc[idx]['title'],
            'score': round(cosine_sim[idx], 3)
        })
    return recommendations


# Streamlit UI

st.title("Keyword-Based Recommendation System 🧠")

st.header("Type a keyword or phrase to get recommendations")
keyword_input = st.text_input("Enter keyword or phrase here:")

if st.button("Get Recommendations"):
    results = get_recommendations_by_keyword(keyword_input)

    if isinstance(results, str):
        st.warning(results)
    else:
        st.success(f"Top recommendations for '{keyword_input}':")
        for i, rec in enumerate(results, 1):
            st.write(f"{i}. {rec['id']} - {rec['title']} (Score: {rec['score']})")
